apiVersion: v1
kind: Service
metadata:
  name: primesigma-service1
  labels:
    name: primesigma-service1
    app: demo-primesigma-app1
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
     name: primesigma-app-pod1
     app: demo-primesigma-app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primesigma-app-deployment
  labels:
    app: demo-primesigma-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: primesigma-app-pod1
      app: demo-primesigma-app1
  template:
    metadata:
      name: primesigma-app-pod1
      labels:
        name: primesigma-app-pod1
        app: demo-primesigma-app1

    spec:
      containers:
      - name: primesigma-app1
        image: cooldsachin/reactjs
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: primesigma-app1
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: primesigma-app1
  targetCPUUtilizationPercentage: 80

