apiVersion: v1
kind: Service
metadata:
  name: json-server-test-service1
  labels:
    name: json-server-test-service1 
spec:
  ports:
  - port: 81
    targetPort: 81
  type: LoadBalancer
  selector:
     name: json-server-test-pod1     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server-test
  labels:
    app: json-server-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: json-server-test
  template:
    metadata:
      labels:
        app: json-server-test
    spec:
      containers:
      - name: json-server-test
        image: clue/json-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 81
